---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBvDDSe9qrA2IjyiGwSi1Lgm8wFDZwORNl5V6OqV7z3w1skKg8onGd6KW9NPjdPUBnfHX/cYssriw9Mwbx/bHqnTXtdv6SHN7ImxiKz2dmlckeBI+R+M610y8j9EZ789H7xIiI0i4axbQC/2mfJsSCwggNlvkF5VZLJ5fux00Knj9Bma1s+xzh43FPDNinYbghMkL74QySKRaPYg0gUIexbbLZwYqulp2KjBqM1rGsRh4xW6nrol0wJmhMJmX7KyvMfr4mQ1QD7hg1Gwg6roM8kq2QRQiQeLwbk24h5j9/IJ/9yRRYHds/zQ0pHZWPokGInni23AUC1h+UU+n9h3pGCwLd2OSRHdZupsn6BZzN5uzvcoRNcC9psXRS6ChEi/2iwSeFo99c0L2lr6rR5y7NswoOys34MAZrQ19boeIeWfHLCDkMC3BGeLKl3Srn/ceID/B15XWdKxCSPwZD4RtmN5xreSov7nv6l05mWU24Cih3QwqG+Ro6Ntl/f7ieTCPzn07KcJdCao0pU8xPGbc/mMrtqwN3+YSBnR3ehbAnWb2M8X4dl1iBmIOSFM/af95xjLWdxcEyATq5OIAQH9MCL9SSTMEJLUgEj/KYQYIFGdzxIYu/5NrkGlzAEtjqyv22QHYiRURIO1IHYaURbKvccJhqPDSLFuh5TJ4+puBPOmnWnKReLuuuWKgtejNEaO9q9D/SZasyTYCHIlTbHKc3fklaCwIdav4IkHLQUkqRa4AehPspPNJjjP52lLz9zrXJPhm3inuModg2PRqv5jmnkjuWdVL1ps8JDP7Ms8Gg7jOOLBeEz9YlCt9j9wJDDbZh99OCA2W/jB0SqBsG9RTFmmMBDVynA2GicZiz+cG48PC4SZ+ShGZ6IhwO2QXfVE8tajuEa655jS0MZCuA/6G5h/5a/fZuPhmQuKPDRtuQz
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflare
