---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgA96fp32WAvntbTNtq5+bSrw7bsxhiAKUxuADVPG6VNZ38DQ21anR9ZxR07WrUxE+/RU1MvVwhTIZyxaA6A0LJSH6u6R3c+b5I6ylpDuYJVadR+dVVBg4tZvHA4M6qnpEwcmK7BAEQL31j6mOUFLM7TNtA33ORVqN32+sjelE5LiQ0JgTuEwEQtg5iauZILj1QfkflZhG96Xo0i6ytmuFZUdYFj5AXXlYxjjiDqpVleb+erowjlpUveSuRhxb0leV5pJHWcblmv2lUT0vsTiagnqgn567unFfJr1WASwX9YZ10hJ38pFkgEWYrA/ipXeE08BEpWzOrS/Leq19ICl/e/nD2YbqoBGZ1OAoF+NHaESb6MmY+kmCbwct52juRdaPfhQCJvzwqtsPyb8eYmJcs64UjZoLq1psgBlZ0J6OBQBs052cSn5S0ir+Ebmk4gnJffh8k/VH+1fNWsXW4HYXmCue/3LHHJZXQPgdn8blXuk3xxA2ZA52DEPcaOy9Op4w3jOJkATQJoFUTIfuPweaIPXaFGT1iZHCofxAlRAMewB0hMpIegrlOsFIcqSW1QTYh3eiXTrDJmSN895an8MfDvNqf9sSQkjRtCLzqFCcNMxhtrqgWP4SEpZEhH3JOYEkyMUJB8/R9C9ujvol/ntJCE9DJxwPPhqWAZ6ZSF5mmxkMdXJtMTd06VVX23QE8GI6VmUW/2HXl9Uj74j0gSHXYCBs+heUAEspmZIFMfb5UMi7/qE8jWSdsrU0vsmPbIiWuh1igC/hSQGJ1KC9yLdM4q5EcKN8LC6s7qToMG7bqXtMkNckU9antrwWyfwV+Vdtws/IkKc5JHGXswwR8sawhWkQIW1rnmepaEziN02m78/RdMP4T0Ews7LOhTAFcoP1+69Bdiw/ic/69QIqKzuVrbWCFK5xbbAv0MIgeBxwR3
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
