# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt@danieldias.ca
    privateKeySecretRef:
      name: letsencrypt-prod-secret
    solvers:
    - selector: {} # This will match all domains
      dns01:
        cloudflare:
          email: danielndias@proton.me
          apiTokenSecretRef:
            name: cloudfare-secret
            key: api-key